version: '3.12'

networks:
  backend:

services:
  postgredb:
    image: 'postgres:15'
    volumes:
      - postgres_data:/var/lip/postgresql/data
    environment:
      POSTGRES_DB: 'velodrive_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgredb

volumes:
  postgredb_data: